### PR TITLE
367 Fix for multiple map instances displaying

### LINKED ISSUE #367: Maps metabox shows 3 instances on saving.
Initially the map metabox displays correctly and the correct value is being stored in the database:

```a:3{s:3:"lat";s:18:"53.800755400000014";s:4:"long";s:19:"-1.5488950097869747";s:9:"elevation";s:17:"49.35803604125977";}```

However once you've clicked update 3 instances of the map are being loaded, all of which show the incorrect value.

screen shot 2016-11-21 at 09 13 38

Here's the code to generate the box:

```php
<?php
  function test_google_maps(array $meta_boxes) {
    $fields = array(
      array( 'id' => 'testing_google_map', 'name' => 'Location', 'type' => 'gmap', 'google_api_key' => get_option('test_gmaps_key') ),
    );

    $meta_boxes[] = array(
      'title' => 'Google Map',
      'pages' => 'page',
      'fields' => $fields,
      'show_on' => array( 'page-template' => array( 'template-home.php' ) ),
    );

    return $meta_boxes;
  }

  add_filter( 'cmb_meta_boxes', 'test_google_maps' );
?>
```

### PR DESCRIPTION
**Pull request by mikeselander**
We were getting multiple map instances displaying after saving a Google Maps field because the  `display` field was splitting the 4 subfield values into their own `html` display. Fixed this with a custom `get_values` method and also split the field into its own file.

This change looks way bigger than it actually is. There's about 4 lines of actually new code.

Resolves #367

*I have:*
 - [x] Run WordPress VIP PHPCS check and code parses without errors
 - [x] Added any new PHPUnit tests
 - [x] Run PHPUnit and all tests are passing after adding any necessary new tests
 - [x] Tested feature/bugfix on single and multisite install

### CODE REVIEW

File: fields/class-cmb-gmap-field.php [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+		) );
+
+	}
+
+	/**
+	 * Get multiple values for a field.
+	 *
+	 * @return array
+	 */
+	public function &get_values() {
```
Comment (rmccue) [inline fields/class-cmb-gmap-field.php]: Probably don't need to return by reference here.

Comment (mikeselander) [inline fields/class-cmb-gmap-field.php]: Agreed, but the parent method is set to return by reference and haven't yet had time to suss out why yet. On my list to address in future 👍

Comment (rmccue) [inline fields/class-cmb-gmap-field.php]: Figured that may be the case :)
